Bulk export
equinor/ecl2df pull request #442
Opened 2023-05-08 07:48 UTC by daniel-sol

Bulk export of data with metadata

2023-05-08 08:43 UTC, perolavsvendsen commented on ecl2df/common.py
> +        tagname=re.sub(r"\..*", "", tagname),
Consider separating into small function, and explicitly test.

2023-05-08 10:49 UTC, berland commented on ecl2df/common.py
> +def set_name_from_args(args):
I don't quite get what this is doing from reading the function name in the context of common.py. Can it get a more descriptive name, optionally an example in the docstring?

2023-05-15 13:55 UTC, berland requested changes
Not having been involved earlier, but summoned to review I have some questions:

* What is the issue? (as an issue in ecl2df isse tracker)
* Why does this functionality belong inside the ecl2df repository (there are probably reasons, I am asking control questions)
* Why can't this be a shell script outside of ecl2df (or in a different repo as python code)
* ecl2df, by its name, is about converting from/to eclipse data to/from dataframes. Is this PR within that scope, or is it stretching it (by being glue code from dataframes to other systems?) (I know, there is code already in ecl2df that is stretching this original intention).
* This PR adds more 5000 lines, which is very significant in terms of lines already existing. Can the added features from this PR defend that many lines, giving the associated extra future maintenance burden?
* There looks to be API breaks in the PR. This should be sorted out, preferably in separate PRs. If ecl2df needs to be changed in order to facilitate the PR, having these changes as "preporatory" PRs would be nice, making each change in the git history understandable later.
* There is already "metadata" support in ecl2df, as in https://github.com/equinor/ecl2df/blob/744394994eafb60014d6b7436c39339cf8894957/ecl2df/summary.py#L418 f.ex. How does this relate to the new "metadata" stuff?

2023-05-15 13:55 UTC, berland commented on ecl2df/bulk.py
> +    """Bulk uploads every module to sumo with metadata
where does sumo come into play in this function? Is this functionality only available with sumo?

2023-05-15 13:55 UTC, berland commented on ecl2df/compdat.py
> +        default=None,
API breaking change?

2023-05-15 13:55 UTC, berland commented on ecl2df/common.py
>      output: str,
I don't like changing this arg from a well-defined string to a big and complex object (an argparse.Namespace), making it enormously harder to test. Can this be refactored?

2023-05-15 13:55 UTC, berland commented on ecl2df/faults.py
> +        args,
The function should not be given all of the args, you only want to provide the absolute minimum number of inputs it needs.

2023-05-15 13:56 UTC, berland requested changes
Not having been involved earlier, but summoned to review I have some questions:

* What is the issue? (as an issue in ecl2df isse tracker)
* Why does this functionality belong inside the ecl2df repository (there are probably reasons, I am asking control questions)
* Why can't this be a shell script outside of ecl2df (or in a different repo as python code)
* ecl2df, by its name, is about converting from/to eclipse data to/from dataframes. Is this PR within that scope, or is it stretching it (by being glue code from dataframes to other systems?) (I know, there is code already in ecl2df that is stretching this original intention).
* This PR adds more 5000 lines, which is very significant in terms of lines already existing. Can the added features from this PR defend that many lines, giving the associated extra future maintenance burden?
* There looks to be API breaks in the PR. This should be sorted out, preferably in separate PRs. If ecl2df needs to be changed in order to facilitate the PR, having these changes as "preporatory" PRs would be nice, making each change in the git history understandable later.
* There is already "metadata" support in ecl2df, as in https://github.com/equinor/ecl2df/blob/744394994eafb60014d6b7436c39339cf8894957/ecl2df/summary.py#L418 f.ex. How does this relate to the new "metadata" stuff?

2023-05-30 10:28 UTC, daniel-sol commented
Will split into more managable PR's

2023-05-30 10:28 UTC, closed without merging